language: python

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install --upgrade pip==18.0 #there is bug with pip 18.1 and pipenv
  - pip install pipenv==2018.7.1
  - pipenv install 
  - pipenv install --dev

script:
  - pytest

deploy:
  provider: heroku
  api_key:
    secure: B30/ZKnQaVnjyA+Q9fmsFs9kaGz/GEt8XehBdMzbO/KGqkUONNW830qCBT6J4/5YcOSuJ4tZgzsCQUIbzl9gtpKHxQwxJH5qYz8KLDgR+c0FzMBxKppKsbMvhDW5osYPizy5EeKnz46uuvslKS8mvaH3JxEJlFwSJMudpRqjVmBeaXxYzglwXxYHBvHyEd1RAg00fKaH3GW0KZkGcUyN0fU31A2TzlZm2x9U94xf5EG99Jnc/0YUtkSYBrj3quS24VDaDtAF69eduH7IIy4uOFGdGLhbapdPM3yMmNFdX2eCahoScj06H3TRedzMlbNy19PuIwyNH8p+o3mIkSBd/vnF5yY6G9KblXWOEGd6p+JpIcdV7UY337JaY2jgzu0b9BA+UwZPcPFDowzLDvufo0duLhlWyabVavdfrynNtwyvWib0Dhc2Idgz9ndI80AePONUB38VnDeMxWKTeruq/5KNO0MGCSEj7VlcPNk6LKvHFZVktmHYadWu/KESW22UMcgxGhLCQGjhG5PZfiSEDny6Yr/M1LMEii0jArfuSAPKEINSG8Tl/SgcQSej9WvPwmir9ORnpzK6AeTWyxhLsCkgfNgtuWnaPPCCsn4z5ml0kodiO1IazLMR3fxSvy2kmITPdVyPvowKkfP6bUWmOd39D0lHpF60RKkO48UWw0A=
  app: ubike-station
  on:
    repo: louis222220/ubike-station
