DROP TABLE IF EXISTS favoriteStation;
DROP TABLE IF EXISTS stations;

CREATE TABLE favoriteStation (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  stationNo INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE stations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    stationNo INTEGER NOT NULL
);